package com.official.senestro.core;

import java.util.HashMap;

public class CountriesList {

    public static HashMap<String, Integer> getShortCodes() {
        HashMap<String, Integer> codes = new HashMap<>();
        codes.put("DZ", 213);
        codes.put("AD", 376);
        codes.put("AO", 244);
        codes.put("AI", 1264);
        codes.put("AG", 1268);
        codes.put("AR", 54);
        codes.put("AM", 374);
        codes.put("AW", 297);
        codes.put("AU", 61);
        codes.put("AT", 43);
        codes.put("AZ", 994);
        codes.put("BS", 1242);
        codes.put("BH", 973);
        codes.put("BD", 880);
        codes.put("BB", 1246);
        codes.put("BY", 375);
        codes.put("BE", 32);
        codes.put("BZ", 501);
        codes.put("BJ", 229);
        codes.put("BM", 1441);
        codes.put("BT", 975);
        codes.put("BO", 591);
        codes.put("BA", 387);
        codes.put("BW", 267);
        codes.put("BR", 55);
        codes.put("BN", 673);
        codes.put("BG", 359);
        codes.put("BF", 226);
        codes.put("BI", 257);
        codes.put("KH", 855);
        codes.put("CM", 237);
        codes.put("CA", 1);
        codes.put("CV", 238);
        codes.put("KY", 1345);
        codes.put("CF", 236);
        codes.put("CL", 56);
        codes.put("CN", 86);
        codes.put("CO", 57);
        codes.put("KM", 269);
        codes.put("CG", 242);
        codes.put("CK", 682);
        codes.put("CR", 506);
        codes.put("HR", 385);
        codes.put("CU", 53);
        codes.put("CY", 357);
        codes.put("CZ", 42);
        codes.put("DK", 45);
        codes.put("DJ", 253);
        codes.put("DM", 1809);
        codes.put("DO", 1809);
        codes.put("EC", 593);
        codes.put("EG", 20);
        codes.put("SV", 503);
        codes.put("GQ", 240);
        codes.put("ER", 291);
        codes.put("EE", 372);
        codes.put("ET", 251);
        codes.put("FK", 500);
        codes.put("FO", 298);
        codes.put("FJ", 679);
        codes.put("FI", 358);
        codes.put("FR", 33);
        codes.put("GF", 594);
        codes.put("PF", 689);
        codes.put("GA", 241);
        codes.put("GM", 220);
        codes.put("GE", 7880);
        codes.put("DE", 49);
        codes.put("GH", 233);
        codes.put("GI", 350);
        codes.put("GR", 30);
        codes.put("GL", 299);
        codes.put("GD", 1473);
        codes.put("GP", 590);
        codes.put("GU", 671);
        codes.put("GT", 502);
        codes.put("GN", 224);
        codes.put("GW", 245);
        codes.put("GY", 592);
        codes.put("HT", 509);
        codes.put("HN", 504);
        codes.put("HK", 852);
        codes.put("HU", 36);
        codes.put("IS", 354);
        codes.put("IN", 91);
        codes.put("ID", 62);
        codes.put("IR", 98);
        codes.put("IQ", 964);
        codes.put("IE", 353);
        codes.put("IL", 972);
        codes.put("IT", 39);
        codes.put("JM", 1876);
        codes.put("JP", 81);
        codes.put("JO", 962);
        codes.put("KZ", 7);
        codes.put("KE", 254);
        codes.put("KI", 686);
        codes.put("KP", 850);
        codes.put("KR", 82);
        codes.put("KW", 965);
        codes.put("KG", 996);
        codes.put("LA", 856);
        codes.put("LV", 371);
        codes.put("LB", 961);
        codes.put("LS", 266);
        codes.put("LR", 231);
        codes.put("LY", 218);
        codes.put("LI", 417);
        codes.put("LT", 370);
        codes.put("LU", 352);
        codes.put("MO", 853);
        codes.put("MK", 389);
        codes.put("MG", 261);
        codes.put("MW", 265);
        codes.put("MY", 60);
        codes.put("MV", 960);
        codes.put("ML", 223);
        codes.put("MT", 356);
        codes.put("MH", 692);
        codes.put("MQ", 596);
        codes.put("MR", 222);
        codes.put("YT", 269);
        codes.put("MX", 52);
        codes.put("FM", 691);
        codes.put("MD", 373);
        codes.put("MC", 377);
        codes.put("MN", 95);
        codes.put("MS", 1664);
        codes.put("MA", 212);
        codes.put("MZ", 258);
        codes.put("NA", 264);
        codes.put("NR", 674);
        codes.put("NP", 670);
        codes.put("NL", 31);
        codes.put("NC", 687);
        codes.put("NZ", 64);
        codes.put("NI", 505);
        codes.put("NE", 227);
        codes.put("NG", 234);
        codes.put("NU", 683);
        codes.put("NF", 672);
        codes.put("NO", 47);
        codes.put("OM", 968);
        codes.put("PW", 680);
        codes.put("PA", 507);
        codes.put("PG", 675);
        codes.put("PY", 595);
        codes.put("PE", 51);
        codes.put("PH", 63);
        codes.put("PL", 48);
        codes.put("PT", 351);
        codes.put("PR", 1787);
        codes.put("QA", 974);
        codes.put("RE", 262);
        codes.put("RO", 40);
        codes.put("RU", 7);
        codes.put("RW", 250);
        codes.put("SM", 378);
        codes.put("ST", 239);
        codes.put("SA", 966);
        codes.put("SN", 221);
        codes.put("CS", 381);
        codes.put("SC", 1758);
        codes.put("SL", 232);
        codes.put("SG", 65);
        codes.put("SK", 421);
        codes.put("SI", 963);
        codes.put("SB", 677);
        codes.put("SO", 252);
        codes.put("ZA", 27);
        codes.put("ES", 34);
        codes.put("LK", 94);
        codes.put("SH", 290);
        codes.put("KN", 1869);
        codes.put("SD", 249);
        codes.put("SR", 597);
        codes.put("SZ", 268);
        codes.put("SE", 46);
        codes.put("CH", 41);
        codes.put("TW", 886);
        codes.put("TJ", 7);
        codes.put("TH", 66);
        codes.put("TG", 228);
        codes.put("TO", 676);
        codes.put("TT", 1868);
        codes.put("TN", 216);
        codes.put("TR", 90);
        codes.put("TM", 993);
        codes.put("TC", 1649);
        codes.put("TV", 688);
        codes.put("UG", 256);
        codes.put("UA", 380);
        codes.put("AE", 971);
        codes.put("UY", 598);
        codes.put("US", 1);
        codes.put("GB", 44);
        codes.put("UZ", 7);
        codes.put("VU", 678);
        codes.put("VA", 379);
        codes.put("VE", 58);
        codes.put("VN", 84);
        codes.put("VG", 1284);
        codes.put("VI", 1340);
        codes.put("WF", 681);
        codes.put("YE", 967);
        codes.put("ZM", 260);
        codes.put("ZW", 263);
        return codes;
    }

    public static HashMap<String, String> getShortNames() {
        HashMap<String, String> names = new HashMap<>();
        names.put("DZ", "Algeria (+213)");
        names.put("AD", "Andorra (+376)");
        names.put("AO", "Angola (+244)");
        names.put("AI", "Anguilla (+1264)");
        names.put("AG", "Antigua & Barbuda (+1268)");
        names.put("AR", "Argentina (+54)");
        names.put("AM", "Armenia (+374)");
        names.put("AW", "Aruba (+297)");
        names.put("AU", "Australia (+61)");
        names.put("AT", "Austria (+43)");
        names.put("AZ", "Azerbaijan (+994)");
        names.put("BS", "Bahamas (+1242)");
        names.put("BH", "Bahrain (+973)");
        names.put("BD", "Bangladesh (+880)");
        names.put("BB", "Barbados (+1246)");
        names.put("BY", "Belarus (+375)");
        names.put("BE", "Belgium (+32)");
        names.put("BZ", "Belize (+501)");
        names.put("BJ", "Benin (+229)");
        names.put("BM", "Bermuda (+1441)");
        names.put("BT", "Bhutan (+975)");
        names.put("BO", "Bolivia (+591)");
        names.put("BA", "Bosnia Herzegovina (+387)");
        names.put("BW", "Botswana (+267)");
        names.put("BR", "Brazil (+55)");
        names.put("BN", "Brunei (+673)");
        names.put("BG", "Bulgaria (+359)");
        names.put("BF", "Burkina Faso (+226)");
        names.put("BI", "Burundi (+257)");
        names.put("KH", "Cambodia (+855)");
        names.put("CM", "Cameroon (+237)");
        names.put("CA", "Canada (+1)");
        names.put("CV", "Cape Verde Islands (+238)");
        names.put("KY", "Cayman Islands (+1345)");
        names.put("CF", "Central African Republic (+236)");
        names.put("CL", "Chile (+56)");
        names.put("CN", "China (+86)");
        names.put("CO", "Colombia (+57)");
        names.put("KM", "Comoros (+269)");
        names.put("CG", "Congo (+242)");
        names.put("CK", "Cook Islands (+682)");
        names.put("CR", "Costa Rica (+506)");
        names.put("HR", "Croatia (+385)");
        names.put("CU", "Cuba (+53)");
        names.put("CY", "Cyprus South (+357)");
        names.put("CZ", "Czech Republic (+42)");
        names.put("DK", "Denmark (+45)");
        names.put("DJ", "Djibouti (+253)");
        names.put("DM", "Dominica (+1809)");
        names.put("DO", "Dominican Republic (+1809)");
        names.put("EC", "Ecuador (+593)");
        names.put("EG", "Egypt (+20)");
        names.put("SV", "El Salvador (+503)");
        names.put("GQ", "Equatorial Guinea (+240)");
        names.put("ER", "Eritrea (+291)");
        names.put("EE", "Estonia (+372)");
        names.put("ET", "Ethiopia (+251)");
        names.put("FK", "Falkland Islands (+500)");
        names.put("FO", "Faroe Islands (+298)");
        names.put("FJ", "Fiji (+679)");
        names.put("FI", "Finland (+358)");
        names.put("FR", "France (+33)");
        names.put("GF", "French Guiana (+594)");
        names.put("PF", "French Polynesia (+689)");
        names.put("GA", "Gabon (+241)");
        names.put("GM", "Gambia (+220)");
        names.put("GE", "Georgia (+7880)");
        names.put("DE", "Germany (+49)");
        names.put("GH", "Ghana (+233)");
        names.put("GI", "Gibraltar (+350)");
        names.put("GR", "Greece (+30)");
        names.put("GL", "Greenland (+299)");
        names.put("GD", "Grenada (+1473)");
        names.put("GP", "Guadeloupe (+590)");
        names.put("GU", "Guam (+671)");
        names.put("GT", "Guatemala (+502)");
        names.put("GN", "Guinea (+224)");
        names.put("GW", "Guinea - Bissau (+245)");
        names.put("GY", "Guyana (+592)");
        names.put("HT", "Haiti (+509)");
        names.put("HN", "Honduras (+504)");
        names.put("HK", "Hong Kong (+852)");
        names.put("HU", "Hungary (+36)");
        names.put("IS", "Iceland (+354)");
        names.put("IN", "India (+91)");
        names.put("ID", "Indonesia (+62)");
        names.put("IR", "Iran (+98)");
        names.put("IQ", "Iraq (+964)");
        names.put("IE", "Ireland (+353)");
        names.put("IL", "Israel (+972)");
        names.put("IT", "Italy (+39)");
        names.put("JM", "Jamaica (+1876)");
        names.put("JP", "Japan (+81)");
        names.put("JO", "Jordan (+962)");
        names.put("KZ", "Kazakhstan (+7)");
        names.put("KE", "Kenya (+254)");
        names.put("KI", "Kiribati (+686)");
        names.put("KP", "Korea North (+850)");
        names.put("KR", "Korea South (+82)");
        names.put("KW", "Kuwait (+965)");
        names.put("KG", "Kyrgyzstan (+996)");
        names.put("LA", "Laos (+856)");
        names.put("LV", "Latvia (+371)");
        names.put("LB", "Lebanon (+961)");
        names.put("LS", "Lesotho (+266)");
        names.put("LR", "Liberia (+231)");
        names.put("LY", "Libya (+218)");
        names.put("LI", "Liechtenstein (+417)");
        names.put("LT", "Lithuania (+370)");
        names.put("LU", "Luxembourg (+352)");
        names.put("MO", "Macao (+853)");
        names.put("MK", "Macedonia (+389)");
        names.put("MG", "Madagascar (+261)");
        names.put("MW", "Malawi (+265)");
        names.put("MY", "Malaysia (+60)");
        names.put("MV", "Maldives (+960)");
        names.put("ML", "Mali (+223)");
        names.put("MT", "Malta (+356)");
        names.put("MH", "Marshall Islands (+692)");
        names.put("MQ", "Martinique (+596)");
        names.put("MR", "Mauritania (+222)");
        names.put("YT", "Mayotte (+269)");
        names.put("MX", "Mexico (+52)");
        names.put("FM", "Micronesia (+691)");
        names.put("MD", "Moldova (+373)");
        names.put("MC", "Monaco (+377)");
        names.put("MN", "Mongolia (+95)");
        names.put("MS", "Montserrat (+1664)");
        names.put("MA", "Morocco (+212)");
        names.put("MZ", "Mozambique (+258)");
        names.put("NA", "Namibia (+264)");
        names.put("NR", "Nauru (+674)");
        names.put("NP", "Nepal (+977)");
        names.put("NL", "Netherlands (+31)");
        names.put("NC", "New Caledonia (+687)");
        names.put("NZ", "New Zealand (+64)");
        names.put("NI", "Nicaragua (+505)");
        names.put("NE", "Niger (+227)");
        names.put("NG", "Nigeria (+234)");
        names.put("NU", "Niue (+683)");
        names.put("NF", "Norfolk Islands (+672)");
        names.put("NO", "Norway (+47)");
        names.put("OM", "Oman (+968)");
        names.put("PW", "Palau (+680)");
        names.put("PA", "Panama (+507)");
        names.put("PG", "Papua New Guinea (+675)");
        names.put("PY", "Paraguay (+595)");
        names.put("PE", "Peru (+51)");
        names.put("PH", "Philippines (+63)");
        names.put("PL", "Poland (+48)");
        names.put("PT", "Portugal (+351)");
        names.put("PR", "Puerto Rico (+1787)");
        names.put("QA", "Qatar (+974)");
        names.put("RE", "Reunion (+262)");
        names.put("RO", "Romania (+40)");
        names.put("RU", "Russia (+7)");
        names.put("RW", "Rwanda (+250)");
        names.put("SM", "San Marino (+378)");
        names.put("ST", "Sao Tome & Principe (+239)");
        names.put("SA", "Saudi Arabia (+966)");
        names.put("SN", "Senegal (+221)");
        names.put("CS", "Serbia (+381)");
        names.put("SC", "Seychelles (+248)");
        names.put("SL", "Sierra Leone (+232)");
        names.put("SG", "Singapore (+65)");
        names.put("SK", "Slovakia (+421)");
        names.put("SI", "Slovenia (+386)");
        names.put("SB", "Solomon Islands (+677)");
        names.put("SO", "Somalia (+252)");
        names.put("ZA", "South Africa (+27)");
        names.put("ES", "Spain (+34)");
        names.put("LK", "Sri Lanka (+94)");
        names.put("SH", "St. Helena (+290)");
        names.put("KN", "St. Kitts (+1869)");
        names.put("SD", "Sudan (+249)");
        names.put("SR", "Suriname (+597)");
        names.put("SZ", "Swaziland (+268)");
        names.put("SE", "Sweden (+46)");
        names.put("CH", "Switzerland (+41)");
        names.put("TW", "Taiwan (+886)");
        names.put("TJ", "Tajikistan (+992)");
        names.put("TH", "Thailand (+66)");
        names.put("TG", "Togo (+228)");
        names.put("TO", "Tonga (+676)");
        names.put("TT", "Trinidad & Tobago (+1868)");
        names.put("TN", "Tunisia (+216)");
        names.put("TR", "Turkey (+90)");
        names.put("TM", "Turkmenistan (+993)");
        names.put("TC", "Turks & Caicos Islands (+1649)");
        names.put("TV", "Tuvalu (+688)");
        names.put("UG", "Uganda (+256)");
        names.put("UA", "Ukraine (+380)");
        names.put("AE", "United Arab Emirates (+971)");
        names.put("UY", "Uruguay (+598)");
        names.put("US", "USA (+1)");
        names.put("GB", "UK (+44)");
        names.put("UZ", "Uzbekistan (+998)");
        names.put("VU", "Vanuatu (+678)");
        names.put("VA", "Vatican City (+379)");
        names.put("VE", "Venezuela (+58)");
        names.put("VN", "Vietnam (+84)");
        names.put("VG", "Virgin Islands - British (+1284)");
        names.put("VI", "Virgin Islands - US (+1340)");
        names.put("WF", "Wallis & Futuna (+681)");
        names.put("YE", "Yemen (+967)");
        names.put("ZM", "Zambia (+260)");
        names.put("ZW", "Zimbabwe (+263)");
        return names;
    }
}