package com.official.senestro.core.enums;

public enum VoiceRecorderOnStopAction {
    DELETE_RECORD, BROADCAST_RECORD, CONVERT_TO_MP3_AND_BROADCAST, CONVERT_TO_OGG_AND_BROADCAST, CONVERT_TO_WAV_AND_BROADCAST, CONVERT_TO_FLAC_AND_BROADCAST, CONVERT_TO_MP3, CONVERT_TO_OGG, CONVERT_TO_WAV, CONVERT_TO_FLAC
}